#include "Layer.hpp"
#include "ClipperUtils.hpp"
#include "Fill/Fill.hpp"
#include "Geometry.hpp"
#include "Print.hpp"
//#include "PrintConfig.hpp"
#include "Surface.hpp"

namespace Slic3r {

/// Struct for the main attributes of a Surface
/// Used for comparing properties
struct SurfaceGroupAttrib
{
    SurfaceGroupAttrib() : is_solid(false), fw(0.f), pattern(-1) {}
    /// True iff all all three attributes are the same
    bool operator==(const SurfaceGroupAttrib &other) const
        { return is_solid == other.is_solid && fw == other.fw && pattern == other.pattern; }
    bool    is_solid;   ///< if a solid infill should be used
    float   fw;         ///< flow Width
    int     pattern;    ///< pattern is of type InfillPattern, -1 for an unset pattern.
};

/// The LayerRegion at this point of time may contain
/// surfaces of various types (internal/bridge/top/bottom/solid).
/// The infills are generated on the groups of surfaces with a compatible type.
/// Fills an array of ExtrusionPathCollection objects containing the infills generated now
/// and the thin fills generated by generate_perimeters().
void
LayerRegion::make_fill()
{
    this->fills.clear();
    
    const double fill_density          = 100;//this->region()->jconfig.fill_density;
    const Flow   infill_flow           = this->flow(frInfill);
    const Flow   solid_infill_flow     = this->flow(frSolidInfill);
    const Flow   top_solid_infill_flow = this->flow(frTopSolidInfill);
    const coord_t perimeter_spacing    = scale_(this->region()->jconfig.hatch_spacing);// this->flow(frPerimeter).scaled_spacing();

    SurfaceCollection surfaces;
    
    // merge adjacent surfaces
    // in case of bridge surfaces, the ones with defined angle will be attached to the ones
    // without any angle (shouldn't this logic be moved to process_external_surfaces()?)
    {
        Polygons polygons_bridged;
        polygons_bridged.reserve(this->fill_surfaces.surfaces.size());
        for (Surfaces::const_iterator it = this->fill_surfaces.surfaces.begin(); it != this->fill_surfaces.surfaces.end(); ++it)
            if (it->is_bridge() && it->bridge_angle >= 0)
                append_to(polygons_bridged, (Polygons)*it);
        
        // group surfaces by distinct properties (equal surface_type, thickness, thickness_layers, bridge_angle)
        // group is of type SurfaceCollection
        // FIXME: Use some smart heuristics to merge similar surfaces to eliminate tiny regions.
        std::vector<SurfacesConstPtr> groups;
        this->fill_surfaces.group(&groups);
        
        // merge compatible solid groups (we can generate continuous infill for them)
        {
            // cache flow widths and patterns used for all solid groups
            // (we'll use them for comparing compatible groups)
            std::vector<SurfaceGroupAttrib> group_attrib(groups.size());
            for (size_t i = 0; i < groups.size(); ++i) {
                const Surface &surface = *groups[i].front();
                // we can only merge solid non-bridge surfaces, so discard
                // non-solid or bridge surfaces
                if (!surface.is_solid() || surface.is_bridge()) continue;
                
                group_attrib[i].is_solid = true;
                group_attrib[i].fw = (surface.is_top()) ? top_solid_infill_flow.width : solid_infill_flow.width;
               // group_attrib[i].pattern = surface.is_top() ? this->region()->config.top_infill_pattern.value
                    //: surface.is_bottom() ? this->region()->config.bottom_infill_pattern.value
                   // : ipRectilinear;
                    //group_attrib[i].pattern =  ipRectilinear;  // for slm we don't use any other pattern
            }
            // Loop through solid groups, find compatible groups and append them to this one.
            for (size_t i = 0; i < groups.size(); ++i) {
                if (!group_attrib[i].is_solid)
                    continue;
                for (size_t j = i + 1; j < groups.size();) {
                    if (group_attrib[i] == group_attrib[j]) {
                        // groups are compatible, merge them
                        append_to(groups[i], groups[j]);
                        groups.erase(groups.begin() + j);
                        group_attrib.erase(group_attrib.begin() + j);
                    } else {
                        ++j;
                    }
                }
            }
        }
        
        // Give priority to oriented bridges. Process the bridges in the first round, the rest of the surfaces in the 2nd round.
        for (size_t round = 0; round < 2; ++ round) {
            for (std::vector<SurfacesConstPtr>::const_iterator it_group = groups.begin(); it_group != groups.end(); ++ it_group) {
                const SurfacesConstPtr &group = *it_group;
                const bool is_oriented_bridge = group.front()->is_bridge() && group.front()->bridge_angle >= 0;
                if (is_oriented_bridge != (round == 0))
                    continue;
                
                // Make a union of polygons defining the infiill regions of a group, use a safety offset.
                Polygons union_p = union_(to_polygons(group), true);
                
                // Subtract surfaces having a defined bridge_angle from any other, use a safety offset.
                if (!is_oriented_bridge && !polygons_bridged.empty())
                    union_p = diff(union_p, polygons_bridged, true);
                
                // subtract any other surface already processed
                //FIXME Vojtech: Because the bridge surfaces came first, they are subtracted twice!
                surfaces.append(
                    diff_ex(union_p, to_polygons(surfaces), true),
                    *group.front()  // template
                );
            }
        }
    }
    
    // we need to detect any narrow surfaces that might collapse
    // when adding spacing below
    // such narrow surfaces are often generated in sloping walls
    // by bridge_over_infill() and combine_infill() as a result of the
    // subtraction of the combinable area from the layer infill area,
    // which leaves small areas near the perimeters
    // we are going to grow such regions by overlapping them with the void (if any)
    // TODO: detect and investigate whether there could be narrow regions without
    // any void neighbors
    {    // for slm
        coord_t distance_between_surfaces = scale_(this->region()->jconfig.hatch_spacing);
        // std::max(
           // std::max(infill_flow.scaled_spacing(), solid_infill_flow.scaled_spacing()),
            //top_solid_infill_flow.scaled_spacing()
        //);
        
        Polygons surfaces_polygons = (Polygons)surfaces;
        Polygons collapsed = diff(
            surfaces_polygons,
            offset2(surfaces_polygons, -distance_between_surfaces/2, +distance_between_surfaces/2),
            true
        );
            
        Polygons to_subtract;
        surfaces.filter_by_type((stInternal | stVoid), &to_subtract);
                
        append_to(to_subtract, collapsed);
        surfaces.append(
            intersection_ex(
                offset(collapsed, distance_between_surfaces),
                to_subtract,
                true
            ),
            (stInternal | stSolid)
        );
    }

    if (false) {
//        require "Slic3r/SVG.pm";
//        Slic3r::SVG::output("fill_" . $layerm->print_z . ".svg",
//            expolygons      => [ map $_->expolygon, grep !$_->is_solid, @surfaces ],
//            red_expolygons  => [ map $_->expolygon, grep  $_->is_solid, @surfaces ],
//        );
    }

    for (Surfaces::const_iterator surface_it = surfaces.surfaces.begin();
        surface_it != surfaces.surfaces.end(); ++surface_it) {
        
        const Surface &surface = *surface_it;
         //-------Apply SLM Hatching...this fills the hatches 
        
        //BoundingBox bbox = surface.expolygon.bounding_box();
        this->make_hatches(surface);

        //------Apply SLM Hatching Ends Here
        continue;

        if (surface.surface_type == (stInternal | stVoid))
            continue;
        
       // InfillPattern fill_pattern = ipRectilinear;//this->region()->config.fill_pattern.value;
        double density =100;// fill_density;
        FlowRole role = (surface.is_top()) ? frTopSolidInfill
            : surface.is_solid() ? frSolidInfill
            : frInfill;
        const bool is_bridge = this->layer()->id() > 0 && surface.is_bridge();
        
        if (surface.is_solid()) {
            density = 100;
            //fill_pattern = ipRectilinear;//(surface.is_top()) ? this->region()->config.top_infill_pattern.value
                //: (surface.is_bottom() && !is_bridge) ? this->region()->config.bottom_infill_pattern.value
                //: ipRectilinear;
        } else if (density <= 0)
            continue;
        
        // get filler object
        #if SLIC3R_CPPVER >= 11
            std::unique_ptr<Fill> f = std::unique_ptr<Fill>(Fill::new_from_type());
        #else
            std::auto_ptr<Fill> f = std::auto_ptr<Fill>(Fill::new_from_type());
        #endif
        
        // switch to rectilinear if this pattern doesn't support solid infill
        if (density > 99 && !f->can_solid())
            #if SLIC3R_CPPVER >= 11
                f = std::unique_ptr<Fill>(Fill::new_from_type(ipRectilinear));
            #else
                f = std::auto_ptr<Fill>(Fill::new_from_type());
            #endif
        
        f->bounding_box = this->layer()->object()->bounding_box();
        
        // calculate the actual flow we'll be using for this infill
        coordf_t h = this->region()->jconfig.hatch_spacing;//(surface.thickness == -1) ? this->layer()->height : surface.thickness;
        Flow flow = this->region()->flow(
            role,
            h,
            is_bridge || f->use_bridge_flow(),  // bridge flow?
            this->layer()->id() == 0,           // first layer?
            -1,                                 // auto width
            *this->layer()->object()
        );
        
        // calculate flow spacing for infill pattern generation
        bool using_internal_flow = false;
        if (!surface.is_solid() && !is_bridge) {
            // it's internal infill, so we can calculate a generic flow spacing
            // for all layers, for avoiding the ugly effect of
            // misaligned infill on first layer because of different extrusion width and
            // layer height
            Flow internal_flow = this->region()->flow(
                frInfill,
                h,  // use the calculated surface thickness here for internal infill instead of the layer height to account for infill_every_layers
                false,  // no bridge
                false,  // no first layer
                -1,     // auto width
                *this->layer()->object()
            );
            f->hatchspacing = this->region()->jconfig.hatch_spacing;//internal_flow.spacing();
            using_internal_flow = true;
        } else {
            f->hatchspacing = this->region()->jconfig.hatch_spacing;//flow.spacing();
        }
        
       // f->endpoints_overlap = scale_(this->region()->config.get_abs_value("infill_overlap",
           // (unscale(perimeter_spacing) + (f->hatchspacing))/2));
        f->endpoints_overlap = f->hatchspacing/2;
        f->layer_id = this->layer()->id();
        f->z        = this->layer()->print_z;
        f->angle    = Geometry::deg2rad(this->region()->jconfig.hatch_angle);
        
        // Maximum length of the perimeter segment linking two infill lines.
        f->link_max_length = (!is_bridge && density > 80)
            ? scale_(3 * f->min_spacing)
            : 0;
        
        // Used by the concentric infill pattern to clip the loops to create extrusion paths.
        f->loop_clipping =  scale_(this->region()->jconfig.hatch_spacing);//scale_(flow.nozzle_diameter) * LOOP_CLIPPING_LENGTH_OVER_NOZZLE_DIAMETER;
        
        // apply half spacing using this flow's own spacing and generate infill
        f->density =1;//this->region()->jconfig.fill_density/100;
        f->dont_adjust = false;
       
        Polylines polylines = f->fill_surface(surface);
        if (polylines.empty())
            continue;

        

        // calculate actual flow from spacing (which might have been adjusted by the infill
        // pattern generator)
        if (using_internal_flow) {
            // if we used the internal flow we're not doing a solid infill
            // so we can safely ignore the slight variation that might have
            // been applied to f->spacing()
        } else {
            flow = Flow::new_from_spacing(f->spacing(), flow.nozzle_diameter, h, is_bridge || f->use_bridge_flow());
        }

        // Save into layer.
        ExtrusionEntityCollection* coll = new ExtrusionEntityCollection();
        coll->no_sort = f->no_sort();
        this->fills.entities.push_back(coll);
        
        {
            ExtrusionRole role;
            if (is_bridge) {
                role = erBridgeInfill;
            } else if (surface.is_solid()) {
                role = (surface.is_top()) ? erTopSolidInfill : erSolidInfill;
            } else {
                role = erInternalInfill;
            }
            
            ExtrusionPath templ(role);
            templ.mm3_per_mm    = flow.mm3_per_mm();
            templ.width         = flow.width;
            templ.height        = flow.height;
            
            coll->append(STDMOVE(polylines), templ);
        }
    }  

    // add thin fill regions
    // thin_fills are of C++ Slic3r::ExtrusionEntityCollection, perl type Slic3r::ExtrusionPath::Collection
    // Unpacks the collection, creates multiple collections per path so that they will
    // be individually included in the nearest neighbor search.
    // The path type could be ExtrusionPath, ExtrusionLoop or ExtrusionEntityCollection.
    for (ExtrusionEntitiesPtr::const_iterator thin_fill = this->thin_fills.entities.begin(); thin_fill != this->thin_fills.entities.end(); ++ thin_fill) {
        ExtrusionEntityCollection* coll = new ExtrusionEntityCollection();
        this->fills.entities.push_back(coll);
        coll->append(**thin_fill);
    }
}





/**
 * @brief Generates hatch patterns within a specified bounding box for a given set of polylines.
 *
 * This method divides the bounding box into a grid of rectangular cells based on the region's
 * island width and height, with a specified overlap. For each cell, it computes the intersection
 * of the provided polylines with the cell and stores the resulting hatch lines.
 *
 * @param p              The set of polylines to be intersected with the grid cells.
 * @param surface_type   The type of surface for which hatches are being generated.
 * @param bounding_box   The bounding box within which to generate the hatch grid.
 *
 * @note The function performs several validity checks on the region and its configuration.
 *       It pre-allocates memory for efficiency and only creates hatches for cells where
 *       intersections are found.
 */
void LayerRegion::make_hatches(const Surface &surface)
{
    // Check region validity first
    if (this->region() == nullptr) {
        std::cerr << "Error: region is null in make_hatches" << std::endl;
        return;
    }
    
    // Early exit for invalid dimensions
    if (this->region()->jconfig.island_width <= 0 || this->region()->jconfig.island_height <= 0) {
        std::cerr << "Error: invalid island dimensions" << std::endl;
        return;
    }
   
    // Convert dimensions to internal scaling
    coord_t island_LInt = scale_(this->region()->jconfig.island_width);
    coord_t island_HInt = scale_(this->region()->jconfig.island_height);
    coord_t overlapInt = scale_(-0.01);
    
    // Ensure we don't have negative increments
    if (island_LInt <= overlapInt || island_HInt <= overlapInt) {
        std::cerr << "Error: overlap larger than island dimensions" << std::endl;
        return;
    }
    BoundingBox bounding_box = surface.expolygon.bounding_box();
    // Calculate grid size to pre-allocate memory
    size_t grid_width = (bounding_box.max.x - bounding_box.min.x) / (island_LInt - overlapInt) + 1;
    size_t grid_height = (bounding_box.max.y - bounding_box.min.y) / (island_HInt - overlapInt) + 1;
    size_t estimated_grid_size = grid_width * grid_height;
    
    // Pre-allocate memory for the grid polygons
    Polygons rectangularGrids;
    rectangularGrids.reserve(estimated_grid_size);
    
    // Create grid cells
    for (coord_t y = bounding_box.min.y; y < bounding_box.max.y; y += (island_HInt - overlapInt)) {
        for (coord_t x = bounding_box.min.x; x < bounding_box.max.x; x += (island_LInt - overlapInt)) {
            // Create a rectangle as a polygon with 4 points
            Points rectangle;
            rectangle.reserve(4);
            
            rectangle.push_back(Point(x, y));
            rectangle.push_back(Point(x, y + island_HInt));
            rectangle.push_back(Point(x + island_LInt, y + island_HInt));
            rectangle.push_back(Point(x + island_LInt, y));
            
            rectangularGrids.push_back(Polygon(rectangle));
        }
    }

    // Reserve space for hatches based on expected grid size
    this->hatches.reserve(this->hatches.size() + rectangularGrids.size());

    // Process each polygon in the grid
    Lines hatch_lines=generate_fill_lines(surface.expolygon.bounding_box());
          hatch_lines=intersection_ln(hatch_lines, surface.expolygon);

    for (const Polygon& rect : rectangularGrids) {
        //Lines cleanlines=generate_hatches(rect);
       // cleanlines.reserve(p.size() * 2); // Rough estimate
        
       // for (const Polyline& polyline : p) {
           // Lines polyline_lines = polyline.lines();
            Lines intersected_lines = intersection_ln(hatch_lines, rect);
            if (!intersected_lines.empty()) 
                this->hatches.emplace_back(std::move(intersected_lines), surface.surface_type);
               // append_to(cleanlines, std::move(intersected_lines));
           // }
        //}

        // Only create a hatch if we have lines
        //if (!cleanlines.empty()) {
           // this->hatches.emplace_back(std::move(cleanlines), surface_type);
        //}
    }
}

Lines LayerRegion::generate_fill_lines(const BoundingBox& bbox) const
{
    Lines hatches;
    //BoundingBox bbox = surface.expolygon.bounding_box();
    
    Points rectangle;
    rectangle.reserve(4);
    
    // Add points in clockwise order
    rectangle.push_back(Point(bbox.min.x, bbox.min.y));     // Bottom-left
    rectangle.push_back(Point(bbox.min.x, bbox.max.y));     // Top-left
    rectangle.push_back(Point(bbox.max.x, bbox.max.y));     // Top-right
    rectangle.push_back(Point(bbox.max.x, bbox.min.y));     // Bottom-right

    Polygon rect(rectangle);
    coord_t hatch_spacing = scale_(0.1);//this->region()->jconfig.hatch_spacing); // Hatch line spacing in mm
   double angle_deg = 0;
    if(this->_layer->id() % 2 == 0)
        angle_deg = 90;
    else
        angle_deg = 0;

    // Convert angle to radians
    double angle_rad = angle_deg * M_PI / 180.0;

    // Unit direction vector of hatch lines
    Vector dir(std::cos(angle_rad), std::sin(angle_rad));
    Vector normal(-dir.y, dir.x);  // normal to the hatch direction

    // Get bounding box of the input rect
    //BoundingBox bbox;
   // bbox.merge(rect);

    // Diagonal length to ensure full coverage
    coord_t dx = bbox.size().x;
    coord_t dy = bbox.size().y;
    coord_t length = std::sqrt(dx * dx + dy * dy) * 2.0;

    // Center point of the bounding box
    Vector center((bbox.min.x + bbox.max.x) / 2.0,
                  (bbox.min.y + bbox.max.y) / 2.0);

    // Project center onto normal to find initial projection
    coord_t center_proj = center.x * normal.x + center.y * normal.y;
       Lines segs;
    // Generate lines across bounding box along the normal direction
    for (coord_t d = center_proj - length; d <= center_proj + length; d += hatch_spacing) {
        // Compute actual origin by offsetting from center along normal
        Vector origin = center + Vector(normal.x * (d - center_proj), normal.y * (d - center_proj));

        // Hatch line endpoints (extend in both directions along dir)
        Vector p1 = origin - Vector(dir.x * length, dir.y * length);
        Vector p2 = origin + Vector(dir.x * length, dir.y * length);

        // Create a line segment from p1 to p2
        Line seg(Point(p1.x, p1.y), Point(p2.x, p2.y));
      
        segs.push_back(seg);

        // Intersect the line segment with the polygon to clip it
       
        //for (const Line& l : clipped) {
            //Polyline poly;
            //poly.points.push_back(l.a);
            //poly.points.push_back(l.b);
           // hatches.push_back(poly);
       // }
    }
    hatches = intersection_ln(segs, rect);  // This works with Polygon
    return hatches;
}








} // namespace Slic3r
